version: "3.8"

services:
  db:
    image: "${DOCKER_IMAGE}"
    restart: "${DOCKER_RESTART}"
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    environment:
       POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"